from src.domain.entities.item import OwnershipEvent, TrackedItem


class ItemRepository:
    def load(self) -> list[TrackedItem]: ...

    def save(self, items: list[TrackedItem]) -> None: ...

    def append_event(self, event: OwnershipEvent) -> None: ...

    def load_events(self, limit: int = 200) -> list[OwnershipEvent]: ...

    def clear(self) -> None: ...
